### PR TITLE
Update FluxCD Terraform module to use new GitHub SSH public key

### LINKED ISSUE #16: Update FluxCD Terraform module to use new GitHub SSH public key
GitHub changed the SSH public key recently. The Terraform module from this repository which provisions Flux CD relies on it.

More info can be found at https://github.com/fluxcd/source-controller/issues/490.

### PR DESCRIPTION
**Pull request by v-ctiutiu**
Fixes #16

### CODE REVIEW

**Comment by stefanprodan** [comment]
You also need to change the SSH Key format from RSA to ECDSA like so:

```
resource "tls_private_key" "main" {
  algorithm   = "ECDSA"
  ecdsa_curve = "P256"
}
```

GitHub has dropped support for RSA SHA-1 some weeks ago.

**Comment by bikram20** [comment]
Thank you @stefanprodan!

**Comment by stefanprodan** [comment]
@v-ctiutiu @bikram20 I would really appreciate if you could add  DigitalOcean to https://fluxcd.io/adopters/

Thank you!

**Comment by bikram20** [comment]
@stefanprodan For sure! I will have to do some quick checks internally. Will do it a week.

**Pull request merged**
